CREATE TABLE IF NOT EXISTS Data (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    Label TEXT NOT NULL CHECK(LENGTH(Label) <= 128),
    Description TEXT CHECK(LENGTH(Description <= 4096)),
    Created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Changed DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Finished DATETIME,
    DeleteOn DATETIME
);



CREATE TABLE IF NOT EXISTS Difficulties (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    Label TEXT NOT NULL UNIQUE CHECK(LENGTH(Label) <= 128),
    Description TEXT CHECK(LENGTH(Description <= 4096)),
    Recommendation TEXT CHECK(LENGTH(Description <= 1024))
);

CREATE TABLE IF NOT EXISTS Priorities (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    Label TEXT NOT NULL UNIQUE CHECK(LENGTH(Label) <= 128),
    Ordering INTEGER NOT NULL UNIQUE CHECK(Ordering BETWEEN 0 AND 63)
);

CREATE TABLE IF NOT EXISTS Types (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    Label TEXT NOT NULL UNIQUE CHECK(LENGTH(Label) <= 128)
);



CREATE TABLE IF NOT EXISTS Timings (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    TypeID INTEGER NOT NULL,

    Start DATETIME,
    End DATETIME,

    FOREIGN KEY(TypeID) REFERENCES Types(ID)
);

CREATE TABLE IF NOT EXISTS Repeater (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    TypeID INTEGER NOT NULL,

    MonthlyInterval INTEGER CHECK(MonthlyInterval BETWEEN 0 AND 511),
    DailyInterval INTEGER NOT NULL CHECK(DailyInterval BETWEEN 0 AND 511),

    FOREIGN KEY(TypeID) REFERENCES Types(ID)
);


            
CREATE TABLE IF NOT EXISTS Categories (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    DataID INTEGER NOT NULL,
    PriorityID INTEGER NOT NULL,

    FOREIGN KEY(DataID) REFERENCES Data(ID),
    FOREIGN KEY(PriorityID) REFERENCES Priorities(ID)
);

CREATE TABLE IF NOT EXISTS Projects (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    DataID INTEGER NOT NULL,
    CategoryID INTEGER NOT NULL,
    PriorityID INTEGER NOT NULL,

    Expiry DATETIME,

    FOREIGN KEY(DataID) REFERENCES Data(ID),
    FOREIGN KEY(CategoryID) REFERENCES Categories(ID),
    FOREIGN KEY(PriorityID) REFERENCES Priorities(ID)
);
            
CREATE TABLE IF NOT EXISTS Appointments (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    DataID INTEGER NOT NULL,
    ProjectID INTEGER NOT NULL,

    FOREIGN KEY(DataID) REFERENCES Data(ID),
    FOREIGN KEY(ProjectID) REFERENCES Projects(ID)
);

CREATE TABLE IF NOT EXISTS Tasks (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    DataID INTEGER NOT NULL,
    ProjectID INTEGER NOT NULL,
    PriorityID INTEGER NOT NULL,
    DifficultyID INTEGER,

    Expiry DATETIME,

    FOREIGN KEY(DataID) REFERENCES Data(ID),
    FOREIGN KEY(ProjectID) REFERENCES Projects(ID),
    FOREIGN KEY(PriorityID) REFERENCES Priorities(ID),
    FOREIGN KEY(DifficultyID) REFERENCES Difficulties(ID)
);



CREATE TABLE IF NOT EXISTS Worktimelimit (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    CategoryID INTEGER NOT NULL,
    TypeID INTEGER NOT NULL,

    LimitInMinutes INTEGER NOT NULL CHECK(LimitInMinutes BETWEEN 5 AND 4096),

    FOREIGN KEY(CategoryID) REFERENCES Categories(ID),
    FOREIGN KEY(TypeID) REFERENCES Types(ID)
);



CREATE TABLE IF NOT EXISTS TimingInCategory (
    TimingID INTEGER,
    CategoryID INTEGER,

    PRIMARY KEY (TimingID, CategoryID),

    FOREIGN KEY (TimingID) REFERENCES Timings(ID),
    FOREIGN KEY (CategoryID) REFERENCES Category(ID)
);

CREATE TABLE IF NOT EXISTS TimingInProject (
    TimingID INTEGER,
    ProjectID INTEGER,
            
    PRIMARY KEY (TimingID, ProjectID),
            
    FOREIGN KEY (TimingID) REFERENCES Timings(ID),
    FOREIGN KEY (ProjectID) REFERENCES Projects(ID)
);

CREATE TABLE IF NOT EXISTS TimingInAppointment (
    TimingID INTEGER,
    AppointmentID INTEGER,
            
    PRIMARY KEY (TimingID, AppointmentID),
            
    FOREIGN KEY (TimingID) REFERENCES Timings(ID),
    FOREIGN KEY (AppointmentID) REFERENCES Appointments(ID)
);

CREATE TABLE IF NOT EXISTS TimingInTask (
    TimingID INTEGER,
    TaskID INTEGER,
            
    PRIMARY KEY (TimingID, TaskID),
            
    FOREIGN KEY (TimingID) REFERENCES Timings(ID),
    FOREIGN KEY (TaskID) REFERENCES Tasks(ID)
);